name: lr4
description: Mad Flutter Practicum 2025
version: 0.0.1+1
publish_to: none
dev_line_length: 120

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: 1.9.1
  path_provider: 2.1.5 #  для определения пути к директориям на устройстве
  sqflite: 2.4.2 # для работы с локальной базой данных (если потребуется кэширование сложных структур);
  shared_preferences: 2.5.3 # для хранения простых настроек и пользовательских флагов;
  flutter_secure_storage: 9.2.4 # для хранения токенов и другой конфиденциальной информации;
   # Пакеты для управления состоянием
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  # Пакет для сравнения состояний Cubit
  equatable: ^2.0.5
  flutter_native_splash: ^2.3.11
  provider: 6.1.5
  url_launcher: 6.3.1
  http: ^1.2.0 # Для сетевых запросов
  rss_dart: ^1.0.13 # Для чтения новостей RSS
  json_annotation: ^4.9.0 # Для работы с JSON
  intl: ^0.19.0 # Для форматирования дат
  xml: ^6.5.0                # Для парсинга XML от ЦБ РФ
  connectivity_plus: ^6.0.4  # Для проверки подключения к интернету
  logger: ^2.6.2
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0

  build_runner: ^2.4.8 # Запускатор генерации кода
  json_serializable: ^6.7.1 # Генератор кода для JSON

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf
          weight: 500

  assets:
    - assets/icons/
    - assets/fonts/

flutter_native_splash:
  color: "#f9f9f6"
  image: assets/icons/logo.png 
  android_gravity: center
  ios_content_mode: center
  # web_image: assets/icons/logo.png